spring:
    jpa:
        hibernate:
            ddl-auto: create-drop

        show-sql: true

    datasource:
        url: jdbc:mysql://localhost/multiwork?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
        username: demo
        password: demo


logging:
    level:
        com.psalles.multiWork : debug
    pattern:
        console: ${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

# Actuators
management:
    server:
        port: 8081
    endpoints:
        web:
            exposure:
                include: "*"


#Surcharge pour le profil local

crossOrigin: https://localhost:4200

actuator:
    base_url: http://localhost:8081/actuator/

server:
    ssl:
        enabled: true
        key-store: classpath:test.jks
        key-store-password: password
        keyStoreType: JKS
        keyAlias: test