spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/multiwork?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    username: ${usernameDB}
    password: ${passwordDB}

actuator:
  base_url: https://psalles.ovh:8081/actuator

cron:
  duration: ${cronDuration}

crossOrigin: https://psalles.ovh, https://www.psalles.ovh

server:
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/psalles.ovh/keystore.p12
    key-store-password: psalles
    keyStoreType: PKCS12
    keyAlias: tomcat