spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/multiwork?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    username: ${usernameDB}
    password: ${passwordDB}

cron:
  duration: ${cronDuration}

crossOrigin: https://psalles.ovh, https://www.psalles.ovh

server:
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/psalles.ovh/keystore.p12
    key-store-password: psalles
    keyStoreType: PKCS12
    keyAlias: tomcat

twitter:
  api.v2:
    tweet: https://api.twitter.com/2/tweets/
    tweets: https://api.twitter.com/2/tweets/search/recent?query=
    user: https://api.twitter.com/2/users/by/username/
  bearer: ${twitterKey}

meteo:
  url: https://api.openweathermap.org/data/2.5/onecall?lat={lat}&lon={lon}&exclude=minutely,daily&units=metric&appid=${meteoKey}