#spring:
#    jpa:
#        hibernate:
#            ddl-auto: update
#
#        show-sql: true
#
#    datasource:
#        url: jdbc:mysql://localhost/demo?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
#        username: demo
#        password: demo

logging:
  level:
    com.psalles.multiWork: debug
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}


# Actuators
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

twitch:
  url:
    streams_base_url: https://api.twitch.tv/helix/streams?
    users_base_url: https://api.twitch.tv/helix/users?
    follows_base_url: https://api.twitch.tv/helix/users/follows?
    videos_base_url: https://api.twitch.tv/helix/videos?
    extensions_base_url: https://api.twitch.tv/helix/users/extensions?
    games_base_url: https://api.twitch.tv/helix/games?

    logout: https://id.twitch.tv/oauth2/revoke?
  client-id: 048o30kiq54suyv43jio7boaknv8e2
